### ISSUE TITLE
Error when updating plugins with variables

### ISSUE THREAD

**Issue by bedis-elacheche** [dpa99c/cordova-check-plugins#12]
When updating plugins that needs variables (e.g phoengap-plugin-push). The app raises an error even when the variable exists in config.xml file

> Updating 'phonegap-plugin-push'... \
Error adding plugin 'phonegap-plugin-push'
Error: Command failed: cordova plugin add phonegap-plugin-push --save
Error: Variable(s) missing (use: --variable SENDER_ID=value).
Failed to update plugin 'phonegap-plugin-push'

**Comment by dpa99c** [comment]
Yes, plugins with variables are not currently supported, but it's on the todo list

**Comment by fiznool** [comment]
This is really unfortunate, it's a deal breaker. Such a shame because everything else about this project is great. 😞

**Comment by dpa99c** [comment]
@fiznool RTFM:The closing commit fixes this

**Comment by fiznool** [comment]
Thanks, turns out it's an issue with the framework I'm using (Ionic).
