### ISSUE TITLE
Plugin order

### ISSUE THREAD

**Issue by fonini** [dpa99c/cordova-check-plugins#17]
Hi, first of all, thanks for the amazing plugin!
I would like to show the plugins with available updates at the bottom of the console.
When there's many plugins, you have to scroll to the top to see if there's some update available.

**Comment by dpa99c** [comment]
I was actually just thinking the same while testing v2.0.0 on the dev branch - I'll swap this around in v2.0.0 which should be ready to release later today.

**Comment by fonini** [comment]
Awesome, thanks again!
