### ISSUE TITLE
Does not support GitHub URLs with access tokens

### ISSUE THREAD

**Issue by ravemir** [dpa99c/cordova-check-plugins#21]
Hello,

Was just trying it out on one of our Cordova projects, but since most of them are private, we use tokens to bypass authentication and allow access. We usually use URLs of this form:
https://[token]:@github.com/[username]/[repo-name]

However, when using this tool I can't check any repositories added through this form. Here's what's displayed when I run the tool
```
plugin: [plugin name]
source: https://[token]:@github.com/[username]/[repo-name]
installed version: 1.0.3
remote version: UNKNOWN - check remote source is valid
error: Failed to read version from github repo for plugin '[plugin name]': plugin.xml not found - make sure the specified repo contains a Cordova plugin
```
I checked and the repository does include a plugin.xml file, which leads me to believe that something stopped the repository from being checked out.

**Comment by dpa99c** [comment]
The newly published `cordova-check-plugins@3.0.0` should now support inline credentials (token or username/password). Although I don't have access to any private Github repos to test with this (my company uses Bitbucket), the [code is in place](https://github.com/dpa99c/cordova-check-plugins/blob/master/lib/remote.js#L145), so please give it a try and let me know the results.
