### ISSUE TITLE
Light grey color for usage description

### ISSUE THREAD

**Issue by vbraun** [dpa99c/cordova-check-plugins#25]
If your terminal uses a white background (which research says is optimal for reading) then light grey is not a particularly helpful color for the usage description. Maybe just not color it at all?

![cordova-check-plugins](https://user-images.githubusercontent.com/888729/33381675-f17e2b96-d51e-11e7-8030-9aea56f38d07.png)

**Comment by dpa99c** [comment]
The colour is actually being [set to white](https://github.com/dpa99c/cordova-check-plugins/blob/4.0.0/lib/logger.js#L74) but the terminal is mapping it to light grey to make it not completely invisible. I'll make it use the default for log-level messages.

**Comment by dpa99c** [comment]
Published as v4.0.1

**Comment by vbraun** [comment]
Thank you!
