### ISSUE TITLE
strange error on running with --update

### ISSUE THREAD

**Issue by miltonhowe** [dpa99c/cordova-check-plugins#30]
I get the following error:
```
Cannot update plugin 'true' as it is not installed in the project

Failed to update all specified plugins
```

When I run with `--update` without the `=` parameter.

Perhaps a better error indicating how to use it.

**Comment by dpa99c** [comment]
As per [documentation](https://github.com/dpa99c/cordova-check-plugins#--updatemodepluginids): `--update={mode|pluginIds}`

i.e. `--update=auto`, `--update=interactive`, `--update={pluginId[s])` 

but not `--update`

**Comment by miltonhowe** [comment]
You are correct, a detailed examination of the documentation provided the solution, which worked for me. Nonetheless I humbly suggest that the error message when you provide the `--update` flag with no mode parameter could be improved from the one I received.
