### ISSUE TITLE
Enhancement to detect plugins still using UIWebView 

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-check-plugins#49]
Is there any way this plugin could have a switch to see if a plugin is dependent on UIWebView?  There are quite a few apps and developers out there that are scrambling to correctly convert their UIWebView apps over to WKWebView and its damn near impossible to find out which plugins are still using it or referencing which is causing the app to be rejected by the Apple App store.   

My app has been rejected 4 times already and I can't figure out what the culprit is....I am also at the point that if I remove any more plugins the core of my app won't work anymore...which means a complete rewrite and months of time to do - both of which are simply not feasible right now.  

I could see the feature also being adapted for the future to detect other deprecated components and plugins that are using or dependent on them.  It would be very useful to contact plugin owners to update their plugins or fork them for repair or worst case recode not using that plugin.  Otherwise, some of this stuff is like finding a needle in a haystack of needles.

**Comment by dpa99c** [comment]
Unfortunately this is beyond the scope of what this plugin is intended for: managing plugin updates.
There are ways to search your code for UIWebView references that don't require this tool to do it - [see here](https://levelup.gitconnected.com/how-to-find-and-remove-uiwebview-uses-in-your-ios-app-d9395f7baacc)

**Comment by rolinger** [comment]
@dpa99c - ok, understood.  Thanks for the reference too.  I just this note before just asking the same question over on the `diagnostics` plugin.  Sorry for asking twice.  Four 18 hour coding days trying to fix all this and I can barely remember what I did 4 hours ago.
