### ISSUE TITLE
Support for plugins with -dev on the version

### ISSUE THREAD

**Issue by apptoix** [dpa99c/cordova-check-plugins#9]
Hi, 
Previously, I created a bash shell script to update cordova plugins, 
but cordova-check-plugins provides a better implementation.
It works well with plugins versions N.N.N, 
but it would be very helpful if also supports versions N.N.N-dev.
For these plugins it gives an error.

Here are 2 examples where this such problem:
cordova-plugin-network-information
phonegap-plugin-mobile-accessibility

Cheers
Alexandre

**Comment by dpa99c** [comment]
Added to my TODO list

**Comment by apptoix** [comment]
Awesome!

A save and restore feature would be the cherry on the top ;-)

Many times cordova new versions are buggy, it can be very helpful for the system to backup the current version numbers in a different section or file, and in case the new plugin version crash, to be able to rollback to a previous versions.

**Comment by dpa99c** [comment]
Just got around to this. Testing with the current version (`cordova-custom-config@1.0.11`), it seems to handle version with `-dev` OK:  [under the hood](https://github.com/dpa99c/cordova-check-plugins/blob/master/index.js#L229), it uses [semver](https://github.com/npm/node-semver) which should handle pre-release tags such as `-dev` correctly. 

Please let me know if there's a scenario where this is not working.

**Comment by dpa99c** [comment]
Reopen if still an issue
